export const GET_QUESTIONS = 'GET_QUESTIONS';
export const GET_ANSWERS = 'GET_ANSWERS';
export const QUESTIONS_SUCCESS = 'QUESTIONS_SUCCESS';
export const ANSWERS_SUCCESS = 'ANSWERS_SUCCESS';
export const SUBMIT_SCORE = 'SUBMIT_SCORE';

export const INCREMENT_STEP = 'INCREMENT_STEP';
